// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_Kc4ADNJ0LwcIA4GnXeXUyfuVuSYq_pA',
    appId: '1:84861660444:web:ccb4a9aa5fbb98b6275ed9',
    messagingSenderId: '84861660444',
    projectId: 'smartkids-edu-platform',
    authDomain: 'smartkids-edu-platform.firebaseapp.com',
    storageBucket: 'smartkids-edu-platform.firebasestorage.app',
    measurementId: 'G-JCQSPJF9QW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCS5ssnWW5yloV5wQat_Qz3YksS8u4evyo',
    appId: '1:84861660444:android:3c3bf314444af1b7275ed9',
    messagingSenderId: '84861660444',
    projectId: 'smartkids-edu-platform',
    storageBucket: 'smartkids-edu-platform.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBc2cKTkJQWUrVfrAbiRFJuTCbOngkpDsI',
    appId: '1:84861660444:ios:f81bc1020e0ff164275ed9',
    messagingSenderId: '84861660444',
    projectId: 'smartkids-edu-platform',
    storageBucket: 'smartkids-edu-platform.firebasestorage.app',
    iosBundleId: 'com.smartkids.smartkidsProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBc2cKTkJQWUrVfrAbiRFJuTCbOngkpDsI',
    appId: '1:84861660444:ios:f81bc1020e0ff164275ed9',
    messagingSenderId: '84861660444',
    projectId: 'smartkids-edu-platform',
    storageBucket: 'smartkids-edu-platform.firebasestorage.app',
    iosBundleId: 'com.smartkids.smartkidsProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC_Kc4ADNJ0LwcIA4GnXeXUyfuVuSYq_pA',
    appId: '1:84861660444:web:14559349f4127633275ed9',
    messagingSenderId: '84861660444',
    projectId: 'smartkids-edu-platform',
    authDomain: 'smartkids-edu-platform.firebaseapp.com',
    storageBucket: 'smartkids-edu-platform.firebasestorage.app',
    measurementId: 'G-3NWM6XVJPJ',
  );
}
